export const STATES = {
  PENDING: "PENDING",
  UPLOADED: "UPLOADED",
  VERIFIED: "VERIFIED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED"
};

export const STATE_LIST = Object.values(STATES);

